version: '3.8'

services:
  # Next.js Development Server
  ctf-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
      # Mount environment file
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - ctf-network
    command: npm run dev

networks:
  ctf-network:
    driver: bridge


